### PR TITLE
Add tags to Pumping model

### PR DESCRIPTION
**Pull request by btoconnor**
Issue: #584 

This adds tags to the Pumping model.

Note: As also mentioned in #576 - I am having troubles with the test suite running properly. I got a bunch of failures unrelated to the Pumping model.  I might try recreating the environment, but if there's any guidance there it would be appreciated.  Apologies if the test suite fails on this - it was hard to get signal on it - hoping the Github checks will give some insight.

### CODE REVIEW

**Review by cdubz — CHANGES_REQUESTED** [review]
@btoconnor this looks good for getting the tag relationship on there. We'll also want to add the tags to the pumping list view and filters. You can see examples of this in the other tag-supported models.

**Comment by cdubz** [comment]
Also FTR I have manually deployed this to http://pr-590.dokku.baby-buddy.net/ -- still haven't had time to try to work out this damn GH action...

**Comment by btoconnor** [comment]
I knew I missed something :)

Will get that going shortly.  Thanks for the tip.

**Comment by cdubz** [comment]
Oh and the API, too! Check out the `TaggableSerializer` and implementation for other models.

**Comment by cdubz** [comment]
Now it looks like we have consistent test fails. That's a good thing! I wonder if we have this on the main branch, too... 👀

**Comment by cdubz** [comment]
Yeah there are inconsistent test fails on the main branch as well. I'll try to get things cleaned up there.

**Comment by cdubz** [comment]
And now we're passing again. Something is definitely wonky here... anyway nothing this PR is doing is causing any fails (:

**Review by cdubz — CHANGES_REQUESTED** [review]
@btoconnor thank you! One last thing -- to implement the tag filtering in the list view `core.filters.PumpingFilter` needs one small change. See the other filters for an example.

**Comment by btoconnor** [comment]
Aha! I didn't even know about that feature - good to know!

**Review by cdubz — APPROVED** [review]
Looks good. Thanks!

**Comment by btoconnor** [comment]
@cdubz Perfect - thanks for the assistance with getting this over the finish line.

Definitely no rush on this - this is pure curiosity - but when do these releases typically make it over to lscr.io for the Docker images?

**Comment by cdubz** [comment]
I think only when I tag releases. I should be more active than I have been lately for the next week or so and I’m surely I’ll do at least one release in that time 😀

**Pull request merged**
