### PR TITLE
Date picker changes

### PR DESCRIPTION
**Pull request by ntrecina**
### Summary
I also noticed a regression from 0a74061a7aedc14734735759cce46d6d5aafc392 where the readonly attribute was removed so mobile browsers were once again displaying the keyboard when tapping on the date picker field. I added the `inputmode=none` attribute which seems like it might be a better solution while still allowing the field to be editable via a keyboard if desired.

### CODE REVIEW

**Comment by cdubz** [comment]
@ntrecina what do you think of the discussion in #284? I think it’s reasonable to allow direct modification of the datetime fields for certain use cases and the UX is not necessarily bad with the keyboard appearing on mobile.

**Comment by cdubz** [comment]
Re: the static files — could you see if you get the same result from `gulp updatestatic`? I don’t _think_ we should be generating FA fonts anymore. Unless they are used in Django admin?

**Comment by ntrecina** [comment]
@cdubz I think it makes sense to have direct modification of date/time fields as mentioned in #284 as I have run into some of the scenarios mentioned. However, I may be wrong but I think the 99% use case on mobile will involve using the gui picker. The keyboard popping up every time you adjust a date/time is a very frustrating user experience. If we were able to come up with a compromise where by default on mobile it doesn't show the keyboard unless you manually chose to I think that would be ideal but as you mentioned I'm not sure if that's possible with the current library.

I'll give `gulp updatestatic` a try, thanks!

**Comment by cdubz** [comment]
@ntrecina could you open a new pr with just the breast milk autoselect change? That seems fine to me but I'd like to invite more discussion about the `inputmode` change.

**Comment by ntrecina** [comment]
@cdubz Sure thing.

**Comment by ntrecina** [comment]
@Expro Do you have any thoughts on this change? From reading your comments on #284 it sounds like you would like to modify date/times via the keyboard on desktop. Would you also like that ability on mobile or do you think gui only control on mobile would be ok?

**Comment by Expro** [comment]
I'm using BabyBuddy almost exclusively on mobile devices, so all my comments are valid for mobile. I still think separate button for GUI picker invocation that is placed adjacent to textboxt containing date and time is superior solution.

**Comment by cdubz** [comment]
@Expro I see -- you are advocating for not showing the _picker_ when clicking in the _field_ but only when clicking the little calendar icon next to the field, right? I'm not sure to what extent that behavior is configurable with the library but that approach does seem like a good middle ground if we can sort it out.

@ntrecina what do you think?

**Comment by Expro** [comment]
That right - I think editable field AND ability to launch picker by button / calendar icon covers both use cases intuitively and would be great if possible (as You have mentioned).

**Comment by ntrecina** [comment]
That seems like a good compromise to satisfy both use cases. That being said I would still prefer an option (user preference maybe) to block keyboard input on mobile since my wife and I don't use it and it's nice having a large target to tap on rather than needing to tap on the calendar to avoid the keyboard opening.

**Comment by cdubz** [comment]
Fair enough, thanks for contributing to the discussion @ntrecina and @Expro. I'm going to merge this change and we'll see how it goes. I think I need to put some more serious thought in to settings organization and options so that I am less overall adverse to adding toggles like this.

**Pull request merged**
