### PR TITLE
Hide cards in dashboard without information

### PR DESCRIPTION
**Pull request by BenjaminHae**

### CODE REVIEW

**Comment by cdubz** [comment]
@BenjaminHae thanks for the contribution!

Have you tested this with an empty DB (a child with no data)? I'm getting the following when I try to go to the dashboard for a child with nothing --

image

**Comment by BenjaminHae** [comment]
> Have you tested this with an empty DB (a child with no data)? I'm getting the following when I try to go to the dashboard for a child with nothing --

Thank you, I did not think of that.

I've now tested it with a clean database and then created some data - seems to work.
Additionally when there is no data, there is now a small indicator that there is no data yet.

**Comment by cdubz** [comment]
Thanks for the update!

I have to admit, I don't necessarily like this behavior. I'd like to see it controllable via a user setting to "hide empty dashboard cards" defaulting to the current behavior (of showing empty cards). Settings are in `babybuddy/models.py` and are available in templates via the `user.settings` global object. A migration will also be needed. Let me know if you'd like to do this work or I can merge this in and then tack it on.

**Comment by BenjaminHae** [comment]
I'd like to give it a try, however it may take a while until I have time to do it.

**Comment by jcgoette** [comment]
Glad to see this PR. Any movement? Can I help in any way?

**Comment by cdubz** [comment]
@BenjaminHae do you still have any intention to come back around to this?

**Comment by BenjaminHae** [comment]
Sorry, I could not find the time. 
@jcgoette if you could implement the change @cdubz requested, that would be nice.

> I have to admit, I don't necessarily like this behavior. I'd like to see it controllable via a user setting to "hide empty dashboard cards" defaulting to the current behavior (of showing empty cards). Settings are in babybuddy/models.py and are available in templates via the user.settings global object. A migration will also be needed. Let me know if you'd like to do this work or I can merge this in and then tack it on.

**Comment by cdubz** [comment]
@jcgoette is this ready for review again? I forgot about it (:

**Comment by jcgoette** [comment]
I'm over in PR #189, but still working on referencing user model in dashboard cards base template. If you notice a simple problem, let me know. Else, I'll figure it out _eventually_. :)

Probably want to close this PR (#137).

**Comment by cdubz** [comment]
Ah yes _that_ was my confusion! Thanks.

**Pull request closed without merging**
