### PR TITLE
Add forms for managing tags

### LINKED ISSUE #460: Add form for managing tags
Currently tags can only be managed in the Django admin interface. Baby Buddy should have a simple tag management UI for admin users to rename, delete, add, and set the color of tags.

### PR DESCRIPTION
**Pull request by MisterPhilip**
Closes #460, adding support for a UI for managing tags. 

Goals for this PR:

- **List all tags**
  - [x] Show a listing of all the tags currently created.
  - [x] Preview the tag color
  - [x] See the number of items that are tagged with the tag
- **Form to add or update tags**
  - [x] Show a form to add a new tag or an update existing tag. Separate from the existing widget.
  - [ ] ~Add a preview tag feature in the form that automatically updates when the color is updated~
  - [x] Show a list of number of items tagged for each item type, linking to the item list with a tag filter automatically applied
- **Delete existing tags**
  - [x] Default item confirmation screen
  - [x] Add warning copy when the tag is in use anywhere
- **List all tagged items for a given tag** 
  - [ ] ~Show all items (TBD if in a single view or in separate tables) that are tagged with this tag~

Added a new menu item:
image

The tag list view, with preview of the color: 
image

The tag detail view, with links to the measurements & activities, pre-filtered to the current filter
image

The tag edit form with default browser color editor:
image

The tag deletion confirmation warning:
image

Other notes - I might be one of the few developing on Windows. I had a few issues with the build scripts and getting the correct line endings to show. What is committed is a _much_ smaller amount than what was coming out prior to editing the build scripts/configs. I have these changes locally but might be worth discussing if they should be merged in (separately) to the repo. Also, I'm not as familiar with Django/Python, so definitely happy to hear any feedback you may have. I figured this would be a good first PR that had some substance 😄

### CODE REVIEW

**Comment by cdubz** [comment]
Thanks for working on this! I’m traveling this weekend but will take a look next week. Curious to see what you found developing from Windows. Baby Buddy has a pretty outdated dev env and build system. I’ve been very slowly trying to bring it up to date but it’s still relying on some long abandoned tooling hah.

**Comment by MisterPhilip** [comment]
Yeah, I'm still tweaking and jotting down notes. I'll eventually split this out into it's own conversation, but for reference with this PR, I've had to:
* Update `_runCommand` to `spawn` as a shell (which _should_ be fine here `_runCommand` never accepts user args)
* Update `.prettierrc` to force set line endings. 
This might have been my editor config, but this helped force the correct setting. You'll note the CI errors are lint based, I suspect only because the default settings vs. my local are still off.

Anyways, I suspect this will be ready for final review sometime next week. The core features are all there, just aiming to complete the stretch goals. 

@cdubz - I could use your feedback on the last stretch goal (" Show all items (TBD if in a single view or in separate tables) that are tagged with this tag"). My idea here is to show everything that is tagged with a given tag. An example where this could be useful is we tag our measurements with "home measurement" or "office measurement", depending on if the measurement was taken at home or the doctor's office. Being able to see all measurements for "office measurement" would give us a quick overview into his official vitals. From the UX side though, I'm not sure if there is a good way to unify everything in a single table. Measurements could probably be rolled into a single table, but then the activities have too many different attributes that might need to be displayed in a single table. We could show a table for all measurements and one for each activity too, but I'm not sure how much easier that would be to parse from the user's perspective. Maybe this would be more useful just as a separate feature with a measurements overview page that could filter down instead of doing it via a tag detail view?

Anyways, this would be the desired output for a given tag:
```
+-----------+--------+--------+------------------+
| Item Type | Child  | Amount |       Date       |
+-----------+--------+--------+------------------+
| Height    | Jane   |     76 | April 23, 2024   |
| Height    | Joe    |     68 | April 23, 2024   |
| Weight    | Joe    |    8.1 | April 22, 2024   |
| Weight    | Joe    |      8 | April 1, 2024    |
| Height    | Joe    |     64 | December 5, 2023 |
+-----------+--------+--------+------------------+
```

**Comment by cdubz** [comment]
> I could use your feedback on the last stretch goal (" Show all items (TBD if in a single view or in separate tables) that are tagged with this tag"). My idea here is to show everything that is tagged with a given tag. An example where this could be useful is we tag our measurements with "home measurement" or "office measurement", depending on if the measurement was taken at home or the doctor's office. Being able to see all measurements for "office measurement" would give us a quick overview into his official vitals. From the UX side though, I'm not sure if there is a good way to unify everything in a single table. Measurements could probably be rolled into a single table, but then the activities have too many different attributes that might need to be displayed in a single table. We could show a table for all measurements and one for each activity too, but I'm not sure how much easier that would be to parse from the user's perspective. Maybe this would be more useful just as a separate feature with a measurements overview page that could filter down instead of doing it via a tag detail view?

Yeah the UI here would be pretty challenging. I think we'd have to show a very limited amount of information about each tag thing and link off to the main entry for more detail. Maybe the timeline page can offer some basic insight? I don't think we would necessarily want to use that _format_ but it does deal with presenting information about all the separate models together.

**Comment by cdubz** [comment]
@MisterPhilip is this one ready for review yet? We still have it marked draft but I'm happy to start taking a closer look when you're ready.

**Comment by MisterPhilip** [comment]
@cdubz - Sorry, was pulled onto a different project recently. I have one more test to fix and then I should be set. I think I'll be able to wrap it up this weekend.

**Comment by MisterPhilip** [comment]
@cdubz all yours for review!

**Review by cdubz — APPROVED** [review]
@MisterPhilip thanks so much for your work here -- this is awesome! Let me see if I can get the rebase conflicts resolved...

**Comment by MisterPhilip** [comment]
Yeah, sorry about that! I had rebased, but I think had selected mine fork instead of the main babybuddy as the origin.

**Comment by cdubz** [comment]
Yeah no worries I just squashed it 😁

**Comment by MrApplejuice** [comment]
Looks lovely @MisterPhilip !

**Pull request merged**
