### PR TITLE
Allow Postgres SSL

### LINKED ISSUE #744: Support Postgres SSL connections
Hello,

I am trying to setup babybuddy using the linuxserver.io image. It seems that babybuddy does not support connecting to postgres using SSL (error output at the bottom). According to this [source](https://stackoverflow.com/questions/47683059/force-ssl-for-django-postgres-connection) I believe adding the following in settings/base.py would support this:

```
if os.getenv("DB_OPTIONS"):
    config["OPTIONS"] = os.getenv("DB_OPTIONS")
```

If this is added, we could use docker with the environment var `DB_OPTIONS: "{'sslmode': 'require'}"`. I can make a pull request for this but I'm not super sure how to compile and test the branch on my own. I this something that could be added? Thank you.

```
OperationalError at /login/
connection to server at "10.10.10.1", port 5432 failed: could not open certificate file "/root/.postgresql/postgresql.crt": Permission denied
connection to server at "10.10.10.1", port 5432 failed: FATAL:  no pg_hba.conf entry for host "10.10.10.1", user "babybuddy", database "babybuddy", no encryption
Request Method: POST
Request URL:    https://redacted
Django Version: 4.2.6
Exception Type: OperationalError
Exception Value:
connection to server at "10.10.10.1", port 5432 failed: could not open certificate file "/root/.postgresql/postgresql.crt": Permission denied
connection to server at "10.10.10.1", port 5432 failed: FATAL:  no pg_hba.conf entry for host "10.10.10.1", user "babybuddy", database "babybuddy", no encryption
Exception Location:     /lsiopy/lib/python3.11/site-packages/psycopg2/__init__.py, line 122, in connect
Raised during:  django.contrib.auth.views.LoginView
Python Executable:      /lsiopy/bin/python3
Python Version: 3.11.6
Python Path:
['/app/www/public',
 '/lsiopy/bin',
 '/usr/lib/python311.zip',
 '/usr/lib/python3.11',
 '/usr/lib/python3.11/lib-dynload',
 '/lsiopy/lib/python3.11/site-packages',
 '/lsiopy/lib/python3.11/site-packages/odf',
 '/lsiopy/lib/python3.11/site-packages/odf',
 '/lsiopy/lib/python3.11/site-packages/odf',
 '/lsiopy/lib/python3.11/site-packages/odf',
 '/lsiopy/lib/python3.11/site-packages/odf',
 '/lsiopy/lib/python3.11/site-packages/odf',
 '/lsiopy/lib/python3.11/site-packages/odf']
Server time:    Thu, 04 Jan 2024 23:21:05 +0000

```

### PR DESCRIPTION
**Pull request by mmomjian**
Fixes #744 

Has not been tested locally as I am unsure how to deploy the source.

### CODE REVIEW

**Comment by mmomjian** [comment]
If this is added, we could use docker with the environment var `DB_OPTIONS: "{'sslmode': 'require'}"`. We could be more specific with creating a flag to specifically enable this variable, but adding an envvar for OPTIONS would seem to be more future-proof.

**Review by cdubz — CHANGES_REQUESTED** [review]
Thanks for contributing! Can you update your PR to also add a note about this to the [database configuration section](https://github.com/babybuddy/babybuddy/blob/master/docs/configuration/database.md)?

**Comment by mmomjian** [comment]
I have added a section in the documentation, thanks.

**Comment by mmomjian** [comment]
I also noticed that the documentation states that the default DB_ENGINE is `django.db.backends.postgresql`, but base.py seems to default to sqlite: `"ENGINE": os.getenv("DB_ENGINE") or "django.db.backends.sqlite3"`. I made updates to the documentation to reflect this.

**Comment by cdubz** [comment]
Merged -- thanks for contributing!

**Pull request merged**
