### PR TITLE
Adding theme support

### PR DESCRIPTION
**Pull request by signorecello**
So I thought I could go a little further in my contributions and add theme support. I also added a light theme (which was the initial idea, I confess), I'm not a designer but google gave me a hand in choosing the colors. I think later we can have an option to make it switch between light and dark according to the timezone?

I also fixed a little typo on my portuguese translation.

Please review, and again, **thank you very much** for this amazing piece of software! My django knowledge was basically zero so this was a good ride!

### CODE REVIEW

**Comment by cdubz** [comment]
Interesting! I’ll need to review this a little deeper (just looking on my phone right now) but this looks very well thought out.

**Comment by signorecello** [comment]
Please do (I also noticed the tests are failing)... I'm gonna have my twin kids literally tomorrow and coding is my way of not thinking/not stressing 😁 so I won't be able to contribute for some weeks now. 

Again thank you very much for this software, learned a lot just reading though it!

**Comment by cdubz** [comment]
Haha no worries. Good luck!!

**Comment by cdubz** [comment]
Ok I smoothed the rough edges on this a bit. The light theme still needs some work though so I'm going to mark this PR WIP for now. Thanks again for getting this started!

**Comment by cdubz** [comment]
Closing this out as it never got picked up and is badly in conflict now. A good template for a future effort, though!

**Pull request closed without merging**
