### PR TITLE
New statistic graphs: Diaper change intervals & feeding intervals

### PR DESCRIPTION
**Pull request by myxor**
New statistic graphs: Diaper change intervals & feeding intervals

grafik

grafik

### CODE REVIEW

**Comment by myxor** [comment]
Feeding intervals statistics works pretty good but there is an issue with the Diaper change intervals statistics as the entries is "left-aligned".  Means the graph starts on the left but the entries do not match the date-value on the x-axis.

Any help to fix this is much appreciated.

**Comment by cdubz** [comment]
@myxor are you still planning to move this PR forward?

**Comment by myxor** [comment]
@cdubz right now i am not planning. I didn't found a solution for issue described in my previous comment yet and therefore i stopped working on this.

Any help would me very much appreciated.

**Comment by garyglatfelter** [comment]
@myxor I think I understand the problem. I think it occurs because your interval lists (_intervals_, _intervals_solid_, _intervals_wet_) will always be length of one shorter than your _changes_ list. One approach might be to simply not pass the first item of _changes_ when you provide x values to be plotted.

In _reports/graphs/diaperchange_intervals.py_:
change 
`x=list(changes.values_list("time", flat=True))` 
to be
`x=list(changes.values_list("time", flat=True))[1:]`

I believe this statement occurs on line 40, line 49, and line 58. Please try that and let me know if that helps.

**Comment by barakplasma** [comment]
I handled the merge changes and @garyglatfelter 's suggestion in https://github.com/barakplasma/babybuddy/tree/continue-pr-444 as a way of testing my PR #707

**Comment by cdubz** [comment]
Nice! Looks like this can also be reviewed in Codespaces now. After we merge #707 I'll take a look at this.

**Comment by cdubz** [comment]
Ok this branch seems out of whack after some bad changes in the last rebase. Not sure how to proceed with it :thinking:

**Comment by barakplasma** [comment]
I can open a new PR with all the git changes sorted out. I still want to provide credit to @myxor for doing the majority of the contribution, but unless they merge in my change / do it themselves... I think it will be a co-author credit?

**Comment by cdubz** [comment]
@barakplasma OK -- and actually you could open it from your branch from @myxor's and they'd still get the commit credits, right?

**Comment by cdubz** [comment]
Changes moved to #710.

**Pull request closed without merging**
