### PR TITLE
lint: running black locally caused mater to fail

### PR DESCRIPTION
**Pull request by billybonks**
Seems to be passing in github, probably a version issue. Local version i am using is 24.1a1. @MrApplejuice was running into the same issue https://github.com/billybonks/babybuddy/pull/2

### CODE REVIEW

**Comment by billybonks** [comment]
seems like ci version 24.1.1 wants to change what my local version wants to do 24.1a1, tried to setup a lock file but failed @cben are you able to hlpe me solve this issue?

**Comment by cdubz** [comment]
Hmmm I wonder why your local version wants 24.1a1? That's a fairly old alpha...

We don't commit a lock file due to differences between architectures. Things may have changed in the past few years to make this doable now but see #43, #41, #146, #199 for all the headaches that came with that.

**Comment by billybonks** [comment]
I will try install a newer version. I got this via pipenv install.

**Comment by cdubz** [comment]
I re-installed my env and did get the latest version. It doesn't make any formtting changes for the current `HEAD` ---

```shell
➜  babybuddy git:(master) pipenv run black --version
Loading .env environment variables...
black, 24.1.1 (compiled: yes)
Python (CPython) 3.10.12
➜  babybuddy git:(master) gulp format
[19:52:40] Using gulpfile ~/PycharmProjects/babybuddy/gulpfile.js
[19:52:40] Starting 'format'...
Loading .env environment variables...
All done! ✨ 🍰 ✨
176 files left unchanged.
[19:52:44] Finished 'format' after 3.47 s
```

**Comment by billybonks** [comment]
I uninstalled then reinstalled works now thanks

**Pull request closed without merging**
