### PR TITLE
fix #699, add diaper change count to card stats

### LINKED ISSUE #699: Feature request: update dashboard DC graph to include "both"
image

It's hard to tell how many diaper changes actually happened when the graph shows wet and solid separately. Could the graph be updated to have a third color for changes that are both?

If I'm just not reading the graph properly then that's fine, it's just tricky to tell how many total changes there have been in a day from this graph.

### PR DESCRIPTION
**Pull request by josevh**
For #699, updated the diaper change card stats to indicate how many diaper changes took place.

I implemented the solution suggested in the issue and added `(x changes)` after the day label. Please advise if it is confusing or if a better alternative is preferred. I also haven't worked with Django translations in a while, please let me know if there are additional changes required on that end.

### Screenshot

image

### CODE REVIEW

**Comment by josevh** [comment]
made a draft while I poke at tests

**Comment by josevh** [comment]
Seeing some errors and failures in the tests (run with Python 3.10.12). They appear unrelated. Run result: https://pastebin.com/m68hAESf

**Comment by cdubz** [comment]
Hm that seems like an odd collection of fails. Will try to take a look at the base tests soon.

**Comment by cdubz** [comment]
@josevh test fails were related to Django 5.x incompatibilities. I have updated `master` to lock Django to 4.x and created #738 to handle that upgrade. If you rebase or merge in `master` tests should pass.

**Comment by josevh** [comment]
@cdubz ty, looks like the rebase onto latest master did the trick for the PR checks. Locally, I still see some errors/failures (Python 3.10.12 and Django 4.2.8) ([paste](https://pastebin.com/9uZtiDEQ)) but that may be expected.

**Comment by cdubz** [comment]
Looks good -- thanks for contributing!

**Pull request merged**
