### PR TITLE
Nav items linking to timeline from dashboard

### LINKED ISSUE #271: Add prominent link to timeline view from dashboard

### PR DESCRIPTION
**Pull request by lutzky**
This is a nav-based option. Note that I'm not sure how to link specifically to the currently-showing child. Also, I'm not fully delighted with the narrow-screen version. See #277 for comparison.

Fixes #271

### CODE REVIEW

**Comment by cdubz** [comment]
@lutzky this is close to ready. Needs tests and documentation and apparently some tweaking (the new icon I added for timers is too big). But you can poke around in the Heroko env if you’re interested.

**Comment by cdubz** [comment]
Also apparently missed the back and forward icons for the timeline 😬

**Comment by lutzky** [comment]
I like it, looks great!

However, it seems that at least one icon is missing: `icon-refresh` is absent, so the timer view has a missing button glyph.

Also, uh, this is marked as being my pull request, which is increasingly inaccurate :rofl:

**Comment by cdubz** [comment]
Thanks for the catch on the refresh icon. I'll get that one fixed.

And you had the branch started so I rolled with it 🤷 

I'm pretty excited about these changes -- it has been fun to see the timeline become a lot more useful and now mature in to more of a core feature. Hopefully it'll lead to even further improvements as people use it more. Or more bugs 😄

**Comment by lutzky** [comment]
Why not both

**Comment by cdubz** [comment]
Ok this is review ready! @lutzky appreciate if you can give it one more look over.

**Comment by cdubz** [comment]
The flexing of the new button groups is a little wonky on my mobile. Will need to think of some way to handle that better but not a huge deal here — 
32F3C6CC-29F0-490F-AABF-6A5980DB2039

**Comment by lutzky** [comment]
Because Github considers this *my* pull request, I can't actually hit "approve" on the review buttons :laughing:

No other breaking changes found, wonky button groups are live-with-able. :shipit:

**Comment by cdubz** [comment]
I've never been bothered by sloppy commits (: Merged! 🚀

**Pull request merged**
