### PR TITLE
Dashboard: Move all "last" cards to top

### LINKED ISSUE #230: Dashboard: Move "Last Diaper Change" to near-top

### PR DESCRIPTION
**Pull request by lutzky**
Fixes #230

### CODE REVIEW

**Comment by BenjaminHae** [comment]
This might be cool on mobile but on a desktop the "latest" cards are on the left. I think this is a bit confusing.

**Comment by lutzky** [comment]
The horizontal positioning on desktop is arbitrary anyway due to "Hide Empty Dashboard Cards".

**Comment by BenjaminHae** [comment]
Only when the cards are empty.

**Comment by cdubz** [comment]
@BenjaminHae yeah considered that but I think it is OK. It would be nice to have them across the top, I think. But having them in a row along the left side also make sense to me as a “most recent information is here” setup. I’ve had a looooooong term plan to make their position fully configurable with a drag-n-drop library (there is an issue somewhere) but have never got around it. Maybe it’s time to revive that idea…

**Pull request merged**
